const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
const LOGOUT = 'LOGOUT';
const LOGIN = 'LOGIN';
const FETCH_SINGLE_SUCCESS = 'FETCH_SINGLE_SUCCESS';
const FETCH_STEPS_ERROR = 'FETCH_STEPS_ERROR';
const FETCH_STEPS_SUCCESS = 'FETCH_STEPS_SUCCESS';
const FETCH_SINGLE_PENDING = 'FETCH_SINGLE_PENDING';
const LOGIN_USER_PENDING = 'LOGIN_USER_PENDING';
const FETCH_STEPS_PENDING = 'FETCH_STEPS_PENDING';
const CREATE_STEP_PENDING = 'CREATE_STEP_PENDING';

export {
  FETCH_STEPS_ERROR,
  FETCH_STEPS_PENDING,
  FETCH_SINGLE_SUCCESS,
  FETCH_STEPS_SUCCESS,
  FETCH_USER_DETAILS,
  CREATE_STEP_PENDING,
  LOGIN,
  LOGOUT,
  FETCH_SINGLE_PENDING,
  LOGIN_USER_PENDING,
};